import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from '../components/Navbar/Index'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Alquran",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
